#docker.io/port/horizon-upgraded-with-really-cool-graphics-and-stuff:future
FROM docker.io/openstackhelm/horizon:ocata
COPY OpenStack_Project_OpenStackHelm_mascot.svg /var/lib/openstack/lib/python2.7/site-packages/openstack_dashboard/static/dashboard/img/logo-splash.svg
RUN chmod 0644 /var/lib/openstack/lib/python2.7/site-packages/openstack_dashboard/static/dashboard/img/logo-splash.svg
