#docker.io/port/horizon-upgraded-with-really-cool-graphics-and-stuff:future
FROM docker.io/openstackhelm/horizon:ocata
ADD https://www.openstack.org/themes/openstack/images/project-mascots/Horizon/OpenStack_Project_Horizon_mascot.png /var/lib/openstack/lib/python2.7/site-packages/openstack_dashboard/static/dashboard/img/logo-splash.svg
